save_ckpt: True
load_ckpt: False
ckpt_pth: './classifier_checkpoints/classifier/with_mapping_80ep/valid_acc=0.963879.pt'
use_map: False
mapping_ckpt: './mapping_checkpoints/map_layer/n_layer=3'

lr: 0.002
n_epoch: 50
batch_size: 1024
