target_dim: 256
source_dim: 256

ot_plan:
  epoch: 10000
  batch_size: 1024
  load_model: False
  load_name: './checkpoints/toy_1130'
  train_model: True

  lr: 0.000001
  alpha: 0.00001
  regularization: 'l2'

mapping:
  epoch: 10000
  batch_size: 1024
  load_model: False
  load_name: './checkpoints/toy_1130'
  train_model: True
  lr: 0.0001
