target_dim: 256
source_dim: 256

ot_plan:
  epoch: 6000
  batch_size: 1024
  load_model: False
  load_name: './checkpoints/toy_1130'
  train_model: True
  save_name: './checkpoints/toy_1130'

  lr: 0.000001
  alpha: 100
  regularization: 'l2'

mapping:
  epoch: 6000
  batch_size: 1024
  load_model: False
  load_name: './checkpoints/toy_1130'
  train_model: True
  save_name: './checkpoints/toy_1130'
  lr: 0.002
