target_dim: 256
source_dim: 256

ot_plan:
  epoch: 6000
  batch_size: 1024
  load_model: False
  load_name: './mapping_checkpoints/entropy/a=100'
  train_model: True

  lr: 0.02
  alpha: 5
  regularization: 'entropy'

mapping:
  epoch: 6000
  batch_size: 1024
  load_model: False
  load_name: './checkpoints/toy_1130'
  train_model: True
  lr: 0.02
